-- CREATE DATABASE IF NOT EXISTS
CREATE DATABASE IF NOT EXISTS hbtn_0c_0;

-- SELECT DATABASE
USE hbtn_0c_0;

-- CREATE TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS first_table (
    id INT,
    name VARCHAR(256)
);
